# Generated by Django 4.2.15 on 2024-09-17 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveBigIntegerField(db_index=True, unique=True, verbose_name='ID Telegram')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Surname')),
            ],
            options={
                'verbose_name': 'Bot User',
                'verbose_name_plural': 'Bot Users',
            },
        ),
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Channel Name')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.botuser', verbose_name='Bot User')),
            ],
            options={
                'verbose_name': 'Telegram Channel',
                'verbose_name_plural': 'Telegram Channels',
            },
        ),
        migrations.CreateModel(
            name='TelegramSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveBigIntegerField(db_index=True, unique=True, verbose_name='ID Telegram')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Surname')),
                ('subscribed', models.BooleanField(default=False, verbose_name='Subscribed')),
                ('datetime_subscribe', models.DateTimeField(blank=True, null=True, verbose_name='Subscription time')),
                ('datetime_unsubscribe', models.DateTimeField(blank=True, null=True, verbose_name='Unsubscription time')),
                ('invite_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramchat', verbose_name='Invitation Link')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
            },
        ),
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creates_join_request', models.BooleanField(default=False, verbose_name='Request to Add')),
                ('creator', models.CharField(blank=True, max_length=250, null=True, verbose_name='Creator')),
                ('expire_date', models.CharField(blank=True, max_length=150, null=True, verbose_name='Expire date')),
                ('link', models.CharField(blank=True, max_length=150, null=True, verbose_name='Link')),
                ('is_primary', models.BooleanField(blank=True, null=True, verbose_name='Is primary')),
                ('is_revoked', models.BooleanField(blank=True, null=True, verbose_name='Is revoked')),
                ('member_limit', models.IntegerField(blank=True, null=True, verbose_name='Subscription limit')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name')),
                ('pending_join_request_count', models.IntegerField(blank=True, null=True, verbose_name='pending_join_request_count')),
                ('telegram_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramchat', verbose_name='Telegram Channel')),
            ],
            options={
                'verbose_name': 'Invitation Link',
                'verbose_name_plural': 'Invitation Links',
            },
        ),
    ]
